blank_issues_enabled: true
contact_links:
  - name: Sukoon Support
    url: https://telegram.me/nillcoderbot 
    about: Please drop your doubts or queries there for an immediate response.
  - name: Documentation
    url: https://telegram.me/nillcoder
    about: Basic documentation for setting up.
